# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@1.5.0
  docker: circleci/docker@2.0.3

jobs:
  unittest-and-linter:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Unittests
          command: python manage.py test
      - run:
          name: Linter
          command: flake8 --max-line-length=99
  
  build-and-push-docker-image:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - setup_remote_docker:
        version: 19.03.13
        docker_layer_caching: true
      - run:
          name: Build and push image Docker
          command: |
          docker build --tag $oc_lettings:$CIRCLE_SHA1 .
          docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASS
          docker tag oc_lettings:$CIRCLE_SHA1 DOCKER_HUB_USERNAME/oc_lettings:$CIRCLE_SHA1
          docker push $DOCKER_HUB_USERNAME/oc_lettings:$CIRCLE_SHA1
        |


workflows:
  sample:
    jobs:
      - unittest-and-linter
      - build-and-push-docker-image
